### ISSUE TITLE
Define standard JSON format for submitting PaperJS paths to DivaServices

### ISSUE THREAD

**Issue by mbaertschi** [mbaertschi/DIA-Distributed#27]
* we need to define in which way we want to submit the paperJS path. what fields are important? where do we want to set the origin of the path ([0,0] e.g. top-left or center of the image?)

**Comment by lunactic** [comment]
Ah I seee.

Yeah that should work out for me. I think I'll probably only need the segments anyways. Do they come in CW or CCW order?

**Comment by mbaertschi** [comment]
Well right now they come in the order you draw :-). Shouldn't matter anyways... I mean you just have to loop over the array and add the segments to the path in that order and the rectangle / polygon should be fine (don't forget to path.closed = true).

**Comment by mbaertschi** [comment]
At least in my application this works :-)

**Comment by lunactic** [comment]
I meant more when you send the POST request to the backend server for processing but it probably doesn't matter as well.

**Comment by mbaertschi** [comment]
If you use some kind of
```
path = new Path
for segment in segments do
  path.addPoint(segment)
path.close()
path.strokeColor = 'black'
```
in your backend, then the form should be ok.

**Comment by lunactic** [comment]
I won't display anything in the backend. I just need it for passing it to the algorithms. Usually the marking is used by the algorithms to only process the selected part of the image.

**Comment by mbaertschi** [comment]
Hmm but this should work as well, shouldn't it? You just have to build the marking bottom up by adding point for point in some kind of manner. Or do I miss something? Well, best thing would be if we simply try it out

**Comment by mbaertschi** [comment]
I mean if you have something like that
![screen shot 2015-05-22 at 11 24 48](https://cloud.githubusercontent.com/assets/1071091/7767734/312eab20-0075-11e5-8800-468a201e11ac.png)
how does cw/ccw helps for identifying the shape?

**Comment by lunactic** [comment]
That's what I meant with "it probably shouldn't matter as well" I don't know the internals of every algorithm in use at the moment.

We just have to document for the future that if you want to use a polygon marking, the response will look like you showed in https://github.com/mbaertschi/DIA-Distributed/issues/27#issuecomment-104576581

**Comment by mbaertschi** [comment]
OK :-)
