### ISSUE TITLE
Add "point" as type of highlighter

### ISSUE THREAD

**Issue by lunactic** [mbaertschi/DIA-Distributed#41]
Hey @mbaertschi 

One thing that I think is missing is output support for single points. 

For example the multiscaleipd algorithm will return you a list of points that should be drawn onto the image. An example of the JSON would look like this:
```
  {
      "scale": 11.199999809265137,
      "score": 0.0,
      "x": 1160.0,
      "y": 38.0
    },
    {
      "scale": 37.79999923706055,
      "score": 0.0,
      "x": 1160.0,
      "y": 40.0
    },
```

I suggest you add *point* as a new type to the list of *highlighter" that you already have in your JSON format and then handle points accordingly. For the first version you don't have to consider the *scale* and *score* present in the example above as not all algorithms might have this information.

**Comment by mbaertschi** [comment]
implemented in 66b66ef48ba0517bc2460793444f38cd1a2a889e. please see docs for schema information.
