### ISSUE TITLE
Offset Problems (maybe when images are too large?)

### ISSUE THREAD

**Issue by lunactic** [mbaertschi/DIA-Distributed#44]
I encounter two different problems when using images that are scaled on the frontend but bigger in the backend:

1. The segments I receive have negative numbers:

```
   "highlighter": {
        "type": "rectangle",
        "closed": true,
        "segments": [
          [
            -260.4307304785894,
            -719.10201511335
          ],
          [
            -260.4307304785894,
            1751.930730478589
          ],
          [
            1061.9874055415614,
            1751.930730478589
          ],
          [
            1061.9874055415614,
            -719.10201511335
          ]
        ]
      },
```

2. The response is not correctly displayed on the frontend:
![image](https://cloud.githubusercontent.com/assets/3973381/8057296/45aaa092-0eb0-11e5-84fa-3df128871a78.png)

To me this seems to be an incorrect computation of values when sending/receiving values on the frontend that have to matched to a scaled image.

@mbaertschi If you want to replicate the bug I can prepare you two JSON files.

**Comment by mbaertschi** [comment]
fixed in 34289c0
