### ISSUE TITLE
[MINOR]: Read out additional Algorithm out of a "info" JSON Object

### ISSUE THREAD

**Issue by lunactic** [mbaertschi/DIA-Distributed#56]
So far I have put additional information into a "info" object as shown below.
This would help to keep the "root" level from an algorithm a bit cleaner.

```
{
  "name": "Artificial Noising",
  "description": "Add artificial noise to an image",
  "url": "http://diufpc59:8080/noise",
  "info": {
    "author": "Mathias Seuret",
    "email": "mathias.seuret@unifr.ch"
  },
  "input": []
}



```

**Comment by mbaertschi** [comment]
implemented in 1ab59e1091ce69b004be7767c1f4fc85f42913c3
@lunactic we have to define a standard time format for expectedRuntime (minutes?)
