### ISSUE TITLE
[MINOR]: Expand results view with an expandable JSON Input / Output viewer

### ISSUE THREAD

**Issue by lunactic** [mbaertschi/DIA-Distributed#59]
On the results page it would be cool if we could have an additional expandable view where we could see the JSON Request and the JSON Response to get a fast intuition on how we could get the same results using some code.

@mbaertschi if you don't get it we can talk about it,

**Comment by mbaertschi** [comment]
I'm not sure if I like this idea :-). You could also just open the javascript console (in chrome) and inspect the request and response payloads. Let's discuss this again ok?

**Comment by mbaertschi** [comment]
Implemented in d4f606a96147a39dfe7cdbfca03ab3bd9c41246d
The request payload is the preprocessed data which is send to server
The response payload is the data which is received from server and is not further postprocessed
